config/routes.rb
Rails.application.routes.draw do


  get    "/login" => "session#new"
  post   "/login" => "session#create"
  delete "/login" => "session#destroy"

  root to: "restaurants#index"

  resources :users, except: [:index]
  resources :restaurants, only: [:show, :index]
  resources :reviews
  get "reviews/:id/like" => "reviews#like", as: "like_review"
  get "user/:id/unlike" => "reviews#unlike", as: "unlike_review"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user, optional: true
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :restaurant

  has_and_belongs_to_many :liked_by, class_name: 'User'

  validates :content, presence: true, length: {maximum: 400}
  validates :rating, presence: true, numericality: { less_than_or_equal_to: 5, greater_than_or_equal_to: 0,  only_integer: true }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :reviews
  has_and_belongs_to_many :liked_reviews, class_name: 'Review'
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def check_if_logged_in
    unless @current_user.present?
      flash[:error] = "You must be logged in to view that page"
      redirect_to login_path
    end
  end

  def fetch_user
    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]

    end

    session[:users_id] = nil unless @current_user.present?
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :fetch_user
  def new
    @restaurant = Restaurant.new
  end

  def create
    # @restaurant = Restaurant.new (restaurant_params)
    # @restaurant.user = @current_user
    # @restaurant.save
    #
    # if @restaurant.persisted?
    #   redirect_to restaurants_path
    # else
    #   flash[:errors] = @restaurant.errors.full_messages
    #   render :new
    # end
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
    @restaurant = Restaurant.find params[:id]
  end

  def edit
  end

  def update
  end

  def destroy
    # unless @restaurant.user == @current_user
    #   redirect_to restaurants_path
    #   return
    # end
    # Restaurant.find(params[:id]).destroy
    # redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :open_hrs, :cost_two, :phone, :user_id, :image)
  end

  # def review_params
  #   params.require(:review).permit(:content, :rating, :restaurant_id, :image)
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :fetch_user
  before_action :check_if_logged_in, except: [:index, :show]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new (review_params)

    # Cloudinary upload happens between .new and .save

    #if file uploaded
    if params[:file].present?
      response = Cloudinary::Uploader.upload params[:file]
      @review.image = response["public_id"]
    end

    @review.user = @current_user
    @review.save

    if @review.persisted?
      restaurant = Restaurant.find params[:review][:restaurant_id].to_i
      # raise "hell"
      redirect_to restaurant_path(restaurant)
    else
      flash[:errors] = @review.errors.full_messages
      render :new
    end


  end


  def index

    # Review.joins(:user).where('name ILIKE :query', query: '%bob%')
    # Review.joins(:user).where('rating >= :val', val: 4)

    if params[:name]
      @reviews = Review.joins(:user).where('name ILIKE :query', query: "%#{params[:name]}%")
    else
      @reviews = Review.all
    end
  end

  def like
    @review = Review.find params[:id].to_i

    # add current user to the liked_by list if the user hasn't liked it
    unless @review.liked_by.include? @current_user
      @review.liked_by << @current_user
    end

    redirect_to review_path(@review)
  end

  def unlike
    @review = Review.find params[:id].to_i

    if @review.liked_by.include? @current_user
      @review.liked_by.delete(@current_user)
    end

    redirect_to review_path(@review)
  end

  def likedreviews
    @user= User.find params[:id]
  end

  def show
    @review = Review.find params[:id]
  end

  def edit
    @review = Review.find params[:id]
  end

  def update
    @review = Review.find params[:id]


    unless @review.user == @current_user
      redirect_to restaurants_path
      return
    end

    if @review.update(review_params)
      if params[:file].present?
        response = Cloudinary::Uploader.upload params[:file]
        @review.image = response["public_id"]
        @review.save
      end

      redirect_to review_path(@review)
    else
      flash[:errors] = @review.errors.full_messages
      render :edit
    end
  end

  def destroy
    @review = Review.find params[:id]
    unless @review.user == @current_user
        redirect_to reviews_path
        return
      else
        @review.destroy
    end

    redirect_to reviews_path
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating, :restaurant_id, :image)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email]

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to (login_path)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :fetch_user
  def new
    @user = User.new
  end

  def create
    user = User.create user_params

    if user.persisted?
      session[:user_id] = user.id
      if params[:file].present?
        response = Cloudinary::Uploader.upload params[:file]
        user.image = response["public_id"]
        user.save
      end
      redirect_to restaurants_path
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]

    unless @user == @current_user
      redirect_to user_path(@current_user)
      return
    end

    if @user.update(user_params)
      if params[:file].present?
        response = Cloudinary::Uploader.upload params[:file]
        @user.image = response["public_id"]
        @user.save
      end
      redirect_to user_path(@current_user)
    else
      flash[:errors] = @user.errors.full_messages
      render :edit
    end

  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisine_helper.rb
module CuisineHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">

  </head>

  <body>
    <div class="mainContainer">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="<%=  %>">H3s</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'Home', restaurants_path, class:'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Reviews', reviews_path, class:'nav-link' %>
            </li>
            <li class="nav-item">
              <% if @current_user.present? %>
                <%= link_to 'My Profile', user_path(@current_user.id), class:'nav-link' %>
              <% else %>
                <%= link_to 'My Profile', login_path, class:'nav-link' %>
                <% end %>
            </li>
          </ul>
          <span class="navbar-text nav-link">
            <% if @current_user.present? %>
              <p class="inlineBlock">Welcome <%= @current_user.name %></p>
              <%= cl_image_tag @current_user.image, class: "profileImage" %>
              <%= link_to 'Log Out', login_path, method: 'delete', class:'nav-link inlineBlock' %>
            <% else %>
              <%= link_to 'Log In', login_path, class:'nav-link inlineBlock' %>
              <%= link_to 'Sign Up', new_user_path, class:'nav-link inlineBlock' %>
            <% end %>
          </span>
        </div>
      </nav>
      <%= yield %>
      <div class="footerBar">
        <div class="container">
          <div class="row">
            <div class="col-8">
              <ul class="footerList">
                <li>Privacy</li>
                <li>Legal</li>
                <li>Terms and Conditions</li>
              </ul>
            </div>
            <div class="col-4 arialFont">© 2018 all rights reserved</div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurant#create</h1>
<p>Find me in app/views/restaurant/create.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurant#edit</h1>
<p>Find me in app/views/restaurant/edit.html.erb</p>

app/views/restaurants/index.html.erb
<div class="d-flex flex-row bd-highlight" id="indexBox">
  <div class="d-flex align-items-start menu">
    <div class="listContainer">
      <ul>
        <% @restaurants.each do |r| %>

          <li class="restaurantList"><%= link_to r.name, restaurant_path(r.id), class:"linkText" %></li>

        <% end %>
      </ul>
    </div>
</div>

  <div class="align-self menuImage">
    <%= image_tag @restaurants.first.image %>
  </div>

</div>

<div class="container descriptionContainer">
  <div class="row">
    <div class="col-6 col-md-4 titleDesc">Good Food Guide's Hat Award</div>
    <div class="col-12 col-md-8">        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed urna erat. Integer ut sem vitae augue feugiat lacinia. Suspendisse lacinia blandit magna at suscipit. Ut laoreet aliquet mi, a commodo eros blandit nec. Nam non elit sit amet ante porta fringilla et laoreet ante. Pellentesque venenatis tincidunt libero, ac pharetra lorem maximus in. Aliquam erat volutpat. Phasellus scelerisque, ligula et interdum tincidunt, ante massa bibendum massa, id iaculis mauris metus et erat. Nullam sed quam ut dui pharetra consequat. Phasellus ac finibus eros, vel pharetra massa. Suspendisse potenti. Aliquam vitae placerat nulla. Suspendisse pharetra interdum augue sagittis suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin commodo molestie interdum.
</div>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>Add a new Restaurant</h1>

app/views/restaurants/show.html.erb
<div>
  <%= image_tag @restaurant.image, class: "bannerPicture" %>
</div>

<nav class="bottomNav navbar navbar-expand-lg navbar-light ">
  <!-- <span class="navbar-text restaurantName">
    <%= @restaurant.name %>
  </span> -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navList navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#desc">Description</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#comments">Comments</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
  </div>
</nav>

<div class="container navGridContainer">
  <a name="desc"></a>
  <div class="row">
    <div class="col-sm">
      <h3>Open Hours</h3>
      <%= @restaurant.open_hrs %>
    </div>
    <div class="col-sm">
      <h3>Location</h3>
      <%= @restaurant.address %>
    </div>
    <div class="col-sm">
      <div>
        <h3>Contact</h3>
        <%= @restaurant.phone %>
      </div>
    </div>
    <div class="col-sm">
      <div>
        <h3>Awarded 3 Hats in</h3>
        <%= @restaurant.year %>
      </div>
    </div>
  </div>
</div>

<div class="container descriptionContainer borderTop">
  <div class="row">
    <div class="col-6 col-md-4 titleDesc"><%= @restaurant.name %></div>
    <div class="col-12 col-md-8"><%= @restaurant.description %></div>
  </div>
</div>


<div class="container commentsContainer">
  <a name="comments"></a>
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="reviewsBox reviewsBoxRestaurant">
        <% @restaurant.reviews.each do |r| %>
          <div class="reviewCard">
            <div class="reviewTitle">
              <p class="inlineBlock floatLeft"><%= cl_image_tag r.user.image, class: "profileImage" %></p>
              <p class="inlineBlock"><%=link_to r.user.name, user_path(r.user) %> on <%=link_to r.created_at.strftime("%D at %I:%M%p"), review_path(r.id) %> about <%= link_to r.restaurant.name, restaurant_path(r.restaurant) %>:</p>
          </div>
            <div class="reviewContent">
              <%= r.content %>
            </div>
            <div class="reviewImageBox">
              <%= cl_image_tag r.image, class: "reviewImage" %>
            </div>
            <div class="favReview">
              Rating: <%= r.rating %> / 5.0 |
              Likes: <%= r.liked_by.length %>
              <% if r.liked_by.include? @current_user %>
                <%= link_to 'Unlike Post', unlike_review_path(r.id), :id => "#{r.id}" %>
              <% else %>
                <%= link_to 'Like Post', like_review_path(r.id), :id => "#{r.id}" %>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
    </div>

    <div class="col-6 col-md-4">
      <div class="titleDesc">
        <p>What others are saying about <%= @restaurant.name %></p>
      </div>
      <button type="button" class="modalShare btn buttonColour" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Share your experience</button>

      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"       aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">

            <div class="container paddingContainer">
              <%= form_for @review, html: {multipart: true} do |f| %>

              <fieldset disabled>
                <div class="form-group">
                  <label for="disabledTextInput">Restaurant</label>
                  <input type="text" id="disabledTextInput" class="form-control" placeholder="<%= @restaurant.name %>">
                </div>
              </fieldset>

              <div class="row">

                  <%= f.label :content, 'Your Experience', for: "exampleFormControlTextarea1" %>
                  <%= f.text_area :content, class: "form-control", id: "exampleFormControlTextarea1", rows: "3"  %>
              </div>

              <div class="row">

                  <%= f.label :rating, for: "formGroupExampleInput" %>
                  <%= f.text_field :rating, class: "form-control", id: "formGroupExampleInput" %>

              </div>

              <div class="row imageRow">

                  <%= f.label :image, for: "exampleFormControlFile1" %>
                  <%= f.cl_image_upload :image, class: "form-control-file", id: "exampleFormControlFile1" %>

              </div>
              <div class="row">
                <div class="form-group">
                  <%= f.hidden_field :restaurant_id, value: "#{@restaurant.id}"%>
                </div>
              </div>
              <%= f.submit %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/restaurants/update.html.erb
<h1>Restaurant#update</h1>
<p>Find me in app/views/restaurant/update.html.erb</p>

app/views/reviews/_form.html.erb
<div class="signUpTitle">
  Add your Experience
</div>

<div class="wrapper">
  <div class="signUpContainer">
    <div class='errors'>
      <% if flash[:errors].present?  %>
         <strong>Please correct the following errors:</strong>
         <ol>
         <% flash[:errors].each do |error| %>
           <li><%= error %></li>
         <% end %>
         </ol>
      <% end %>
    </div>
    <div class="signUpForm">
      <%= form_for @review, html: {multipart: true} do |f| %>
        <div class="inputForm">
          <%= f.label :restaurant_id, 'Restaurant', for: "inputRestaurant" %>
          <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name, prompt: 'Please choose a Restaurant', id: "inputRestaurant", class: "form-control"%>
          <br>
          <div class="input-group resize">
            <div class="input-group-prepend">
              <%= f.label :content, "Your experience", class: "input-group-text" %>
            </div>
          <%= f.text_area :content, class:"form-control", 'aria-label' => "With textarea" %>
          </div>
          <br>
          <%= f.label :rating %>
          <%= f.text_field :rating %>
          <br>
          <%= f.label :image %>
          <%= f.cl_image_upload :image %>
          <br>
        </div>
        <div class="submitBox">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/reviews/edit.html.erb
<h2>Edit Review at  <%= @review.restaurant.name %></h2>

<%= render partial: 'form' %>

app/views/reviews/index.html.erb
<div class="paddingTitle">
  <h2>Activity Feed</h2>
</div>

<div class="container indexReviewBox">
  <div class="row">
    <div class="col">
      <div class="col col-md-8">
        <div class="reviewsBox reviewsScrollIndex">
          <% @reviews.each do |r| %>
            <div class="reviewCard">
              <div class="reviewTitle">
                <p class="inlineBlock floatLeft"><%= cl_image_tag r.user.image, class: "profileImage" %></p>
                <p class="inlineBlock"><%=link_to r.user.name, user_path(r.user) %> on <%= link_to r.created_at.strftime("%D at %I:%M%p"), review_path(r.id) %> about <%= link_to r.restaurant.name, restaurant_path(r.restaurant) %>:</p>
            </div>
              <div class="reviewContent">
                <%= r.content %>
              </div>
              <div class="reviewImageBox">
                <%= cl_image_tag r.image, class: "reviewImage" %>
              </div>
              <div class="favReview">
                Rating: <%= r.rating %> / 5.0 |
                Likes: <%= r.liked_by.length %>
                <% if r.liked_by.include? @current_user %>
                  <%= link_to 'Unlike Post', unlike_review_path(r.id), :id => "#{r.id}" %>
                <% else %>
                  <%= link_to 'Like Post', like_review_path(r.id), :id => "#{r.id}" %>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
      </div>
    </div>

    <div class="col-2 col">
      <%= form_tag(reviews_path, method: :get) do %>
        <%= text_field_tag :name, nil, placeholder: "Enter a name", class: "searchBar" %>
        <%= submit_tag "Search User's Post" %>
      <% end %>
      <br>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="signUpTitle">
  Add your Experience
</div>

<div class="wrapper">
  <div class="signUpContainer">
    <div class='errors'>
      <% if flash[:errors].present?  %>
         <strong>Please correct the following errors:</strong>
         <ul>
         <% flash[:errors].each do |error| %>
           <li><%= error %></li>
         <% end %>
       </ul>
      <% end %>
    </div>
    <div class="signUpForm">
      <%= form_for @review, html: {multipart: true} do |f| %>
        <div class="inputForm">
          <%= f.label :restaurant_id, 'Restaurant', for: "inputRestaurant" %>
          <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name, prompt: 'Please choose a Restaurant', id: "inputRestaurant", class: "form-control"%>
          <br>
          <br>
          <%= f.label :content, "Your experience:" %>
          <%= f.text_area :content, class:"form-control", 'aria-label' => "With textarea" %>
          <br>
          <%= f.label :rating %>
          <%= f.text_field :rating %>
          <br>
          <br>
          <%= f.label :image %>
          <%= f.cl_image_upload :image %>
          <br>
        </div>
        <div class="submitBox">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="paddingTitle">
  <h2><%= @review.user.name %>'s Post made on <%= @review.created_at.strftime("%D at %I:%M%p") %> about <%= link_to @review.restaurant.name, restaurant_path(@review.restaurant) %> </h2>
  <% if @current_user == @review.user %>
    <%= link_to 'Edit Post', edit_review_path(@review) %>
    <%= link_to 'Delete Post', review_path, method: 'delete' %>
  <% end %>
</div>


<div class="container indexReviewBox">
  <div class="row">
    <div class="col">
      <div class="col col-md-8">
        <div class="reviewsBox reviewsScrollIndex">
            <div class="reviewCard">
              <div class="reviewTitle">
                <p class="inlineBlock floatLeft"><%= cl_image_tag @review.user.image, class: "profileImage" %></p>
                <p class="inlineBlock"><%=link_to @review.user.name, user_path(@review.user) %> on <%= link_to @review.created_at.strftime("%D at %I:%M%p"), review_path(@review) %> about <%= link_to @review.restaurant.name, restaurant_path(@review.restaurant) %>:</p>
            </div>
              <div class="reviewContent">
                <%= @review.content %>
              </div>
              <div class="reviewImageBox">
                <%= cl_image_tag @review.image, class: "reviewImage" %>
              </div>
              <div class="favReview">
                Rating: <%= @review.rating %> / 5.0 |
                Likes: <%= @review.liked_by.length %>
                <% if @review.liked_by.include? @current_user %>
                  <%= link_to 'Unlike Post', unlike_review_path(@review), :id => "#{@review.id}" %>
                <% else %>
                  <%= link_to 'Like Post', like_review_path(@review.id), :id => "#{@review.id}" %>
                <% end %>
              </div>
            </div>
          </div>

          <div>
            Liked by:
            <% @review.liked_by.each do |user| %>
              <%= link_to user.name, user_path(user.id) %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/update.html.erb
<h1>Review#update</h1>
<p>Find me in app/views/review/update.html.erb</p>

app/views/users/show.html.erb
<div class="paddingTitle">
  <h2><p class="inlineBlock floatLeft"><%= cl_image_tag @user.image, class: "profileImageLarge" %></p>
    <div class="titleProfile inlineBlock"><%= @user.name %>'s Profile</div>
  </h2>
  <div class="editLink">
    <% if @current_user.present? && @current_user == @user %>
      <%= link_to 'Edit Profile', edit_user_path %>
    <% end %>
  </div>
  <div class="editLink">
    Liked Posts: <%= @user.liked_reviews.length %>
    <% if @user.liked_reviews.length > 0 %>
      <button type="button" class="btn btn-primary modalLiked" data-toggle="modal" data-target=".bd-example-modal-lg">Liked Posts</button>
    <% end %>
    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="reviewsBox reviewsScrollIndex">
            <% @user.liked_reviews.each do |r| %>
              <div class="reviewCard">
                <div class="reviewTitle">
                  <p class="inlineBlock floatLeft"><%= cl_image_tag r.user.image, class: "profileImage" %></p>
                  <p class="inlineBlock"><%=link_to r.user.name, user_path(r.user) %> on <%= link_to r.created_at.strftime("%D at %I:%M%p"), review_path(r.id) %> about <%= link_to r.restaurant.name, restaurant_path(r.restaurant) %>:</p>
              </div>
                <div class="reviewContent">
                  <%= r.content %>
                </div>
                <div class="reviewImageBox">
                  <%= cl_image_tag r.image, class: "reviewImage" %>
                </div>
                <div class="favReview">
                  Rating: <%= r.rating %> / 5.0 |
                  Likes: <%= r.liked_by.length %>
                  <% if r.liked_by.include? @current_user %>
                    <%= link_to 'Unlike Post', unlike_review_path(r.id), :id => "#{r.id}" %>
                  <% else %>
                    <%= link_to 'Like Post', like_review_path(r.id), :id => "#{r.id}" %>
                  <% end %>
                </div>
              </div>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% if @user.reviews.length > 0 %>
<div class="container indexReviewBox">
  <div class="row">
    <div class="col-10">
      <div class="col-12 col-md-8">
        <div class="reviewsBox reviewsScrollIndex">
          <% @user.reviews.each do |r| %>
            <div class="reviewCard">
              <div class="reviewTitle">
                <p class="inlineBlock floatLeft"><%= cl_image_tag r.user.image, class: "profileImage" %></p>
                <p class="inlineBlock"><%=link_to r.user.name, user_path(r.user) %> on <%= link_to r.created_at.strftime("%D at %I:%M%p"), review_path(r.id) %> about <%= link_to r.restaurant.name, restaurant_path(r.restaurant) %>:</p>
            </div>
              <div class="reviewContent">
                <%= r.content %>
              </div>
              <div class="reviewImageBox">
                <%= cl_image_tag r.image, class: "reviewImage" %>
              </div>
              <div class="favReview">
                Rating: <%= r.rating %> / 5.0 |
                Likes: <%= r.liked_by.length %>
                <% if r.liked_by.include? @current_user %>
                  <%= link_to 'Unlike Post', unlike_review_path(r), :id => "#{r.id}" %>
                <% else %>
                  <%= link_to 'Like Post', like_review_path(r.id), :id => "#{r.id}" %>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
      </div>
    </div>

  </div>
</div>
<% else %>
<div class="middleText">
  <span class="smiley">:'(</span>
</div>
<div class="middleText">You have no posts. <%= link_to 'Add a post', new_review_path %></div>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

<div class="col-10">
  <div class="col-12 col-md-8">
    <div class="reviewsBox reviewsScrollIndex">
      <% @user.reviews.each do |r| %>
        <div class="reviewCard">
          <div class="reviewTitle">
            <p class="inlineBlock floatLeft"><%= cl_image_tag r.user.image, class: "profileImage" %></p>
            <p class="inlineBlock"><%=link_to r.user.name, user_path(r.user) %> on <%= link_to r.created_at.strftime("%D at %I:%M%p"), review_path(r.id) %> about <%= link_to r.restaurant.name, restaurant_path(r.restaurant) %>:</p>
        </div>
          <div class="reviewContent">
            <%= r.content %>
          </div>
          <div class="reviewImageBox">
            <%= cl_image_tag r.image, class: "reviewImage" %>
          </div>
          <div class="favReview">
            Rating: <%= r.rating %> / 5.0 |
            Likes: <%= r.liked_by.length %>
            <%= link_to 'Like Post', like_review_path(r.id), :id => "#{r.id}" %>
          </div>
        </div>
        <% end %>
      </div>
  </div>
</div>